[build]
builder = "nixpacks"

[deploy]
startCommand = "python server/app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
